RULE_CATALOGUE = {
    "R01": {
        "title": "Telnet service identified",
        "severity": "high",
        "confidence": "medium",
        "limitations": [
            "This is a local observation from the selected TCP port profile only.",
            "No credentials or login attempts were performed.",
        ],
        "actions": [
            {"action_id": "review_service_need", "text": "Review whether the service is required.", "verification": "Confirm the device's authorised management paths."},
            {"action_id": "use_secure_alternative", "text": "Use a supported secure management method instead.", "verification": "Check the device's secure management configuration."},
        ],
        "references": [{"title": "Telnet guidance", "url": "https://example.com/telnet"}],
        "version": "1.0.0",
        "rule_id": "R01",
    },
    "R02": {
        "title": "FTP service identified",
        "severity": "medium",
        "confidence": "medium",
        "limitations": ["The scan did not validate encrypted transfer support."],
        "actions": [
            {"action_id": "review_service_need", "text": "Review whether the service is required.", "verification": "Check whether the file transfer feature is still needed."},
            {"action_id": "prefer_encrypted_transfer", "text": "Use a supported encrypted transfer method.", "verification": "Verify the device and user paths support consented encrypted transfer."},
        ],
        "references": [{"title": "FTP guidance", "url": "https://example.com/ftp"}],
        "version": "1.0.0",
        "rule_id": "R02",
    },
    "R03": {
        "title": "HTTP service identified",
        "severity": "low",
        "confidence": "medium",
        "limitations": ["The scan did not test HTTPS redirection or page purpose."],
        "actions": [
            {"action_id": "check_https", "text": "Check the device's supported HTTPS configuration.", "verification": "Confirm encrypted management or web access is available and valid."},
            {"action_id": "review_web_exposure", "text": "Review whether the web service is intended to be reachable.", "verification": "Confirm the device is meant to expose a local web interface."},
        ],
        "references": [{"title": "HTTP guidance", "url": "https://example.com/http"}],
        "version": "1.0.0",
        "rule_id": "R03",
    },
    "R04": {
        "title": "Remote desktop service reachable locally",
        "severity": "medium",
        "confidence": "medium",
        "limitations": ["This scan did not test credentials, exposure, or user permissions."],
        "actions": [
            {"action_id": "review_service_need", "text": "Review whether remote desktop access is required.", "verification": "Confirm the service is authorised and necessary."},
            {"action_id": "restrict_access", "text": "Restrict authorised access to the service.", "verification": "Confirm only permitted, known clients can reach the endpoint."},
        ],
        "references": [{"title": "Remote desktop guidance", "url": "https://example.com/rdp"}],
        "version": "1.0.0",
        "rule_id": "R04",
    },
    "R05": {
        "title": "File-sharing service reachable locally",
        "severity": "medium",
        "confidence": "medium",
        "limitations": ["SMB version and permissions were not established by this scan."],
        "actions": [
            {"action_id": "review_sharing", "text": "Review sharing and access rules.", "verification": "Confirm the service exposes only authorised shares or endpoints."},
            {"action_id": "check_permissions", "text": "Check that permissions are limited to necessary users.", "verification": "Verify an approved access model is in place."},
        ],
        "references": [{"title": "File-sharing guidance", "url": "https://example.com/smb"}],
        "version": "1.0.0",
        "rule_id": "R05",
    },
    "R06": {
        "title": "MQTT service reachable locally",
        "severity": "medium",
        "confidence": "medium",
        "limitations": ["The scan did not verify authentication or encryption settings."],
        "actions": [
            {"action_id": "verify_auth", "text": "Verify authentication and authorisation requirements.", "verification": "Confirm only authorised clients can publish or subscribe."},
            {"action_id": "check_encryption", "text": "Check whether transport encryption is required.", "verification": "Verify the broker supports the intended data protections."},
        ],
        "references": [{"title": "MQTT guidance", "url": "https://example.com/mqtt"}],
        "version": "1.0.0",
        "rule_id": "R06",
    },
    "R07": {
        "title": "Open port requires review",
        "severity": "informational",
        "confidence": "low",
        "limitations": ["The service identity is not confirmed enough for a CVE level claim."],
        "actions": [
            {"action_id": "review_service_need", "text": "Review whether the service is required.", "verification": "Check whether the open port is expected and authorised."},
            {"action_id": "verify_service_identity", "text": "Verify the service identity.", "verification": "Confirm the process and version if the port is needed."},
        ],
        "references": [{"title": "General port review", "url": "https://example.com/ports"}],
        "version": "1.0.0",
        "rule_id": "R07",
    },
}
